Repository GlobeHoppin/GlobeHoppin, pull requests merged in 2024-10, with the labels that each got.

#37 Customise the Scrollbar | Issue #25
  src/App.css
Labels: enhancement, help wanted, gssoc-ext, hacktoberfest-accepted, Level1

#46 add faq pop up modal at footer
  src/components/FAQ.jsx
  src/data/faqData.json
  src/pages/Homepage.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#98 add trip budgeter
  src/App.jsx
  src/components/PageNav.jsx
  src/pages/TripBudgetCalculatorPage.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level3

#100 Added hotel booking system
  src/App.css
  src/App.jsx
  src/components/PageNav.jsx
  src/pages/YourBookings.jsx
  src/pages/booking.jsx
  src/pages/famous.jsx
  src/pages/hoteldata.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level3

#92 added load more feature to FAQs
  src/App.jsx
  src/components/FAQ.jsx
  src/data/faqData.json
  src/pages/faq.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#20 #Add Github Actions Bot & Code of Conduct Md file
  .github/workflows/greetings.yml
  Code_Of_Conduct.md
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level1

#47 Fix heading color issues
  src/pages/Homepage.jsx
  src/pages/Loginpage.jsx
  src/pages/Registerpage.jsx
Labels: bug, enhancement, gssoc-ext, hacktoberfest-accepted, Level1

#122 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level1

#99 Add review page
  src/App.jsx
  src/components/PageNav.jsx
  src/pages/Review.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#11 added message functionality to the contact form
  src/ApiEndpoints.jsx
  src/pages/Contactpage.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#154 Multi-Language Support Using Language Translator
  src/components/Footer.jsx
  src/pages/Contactpage.jsx
  src/pages/GoogleTranslate.jsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, Level3
